version: '3.6'
services:
  db:
    container_name: psql
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: ramiro
      POSTGRES_DB: NG
    volumes:
      - ./pgdata:/data/postgresql
    ports:
      - "5432:5432"
  app:
    container_name: node
    restart: always
    build: .
    command: yarn start
    ports:
      - "3001:3001" 
    depends_on:
      - db